{
 "title": "Network Monitoring",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Latency (ms)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select created_on as time\n, case\n     when latency_ms is null then 1000\n     else latency_ms\nend as latency_ms\nfrom latency_metric;"
    }
   ]
  },
  {
   "title": "Download (mbps)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select created_on as time\n, case\n     when download_kbs is null then 0\n     else download_kbs / 1024.0\nend as download_mbps\nfrom bandwidth_metric;"
    }
   ]
  },
  {
   "title": "Upload (mbps)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select created_on as time\n, case\n     when upload_kbs is null then 0\n     else upload_kbs / 1024.0\nend as upload_mbps\nfrom bandwidth_metric;"
    }
   ]
  },
  {
   "title": "Outages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "select created_on as time\n, 1 as outage\nfrom latency_metric\nwhere latency_ms is null or latency_ms = 0;"
    }
   ]
  },
  {
   "title": "Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "select created_on as time\n, case\n     when latency_ms is null then 0\n     else latency_ms\nend as latency_ms\nfrom latency_metric;"
    }
   ]
  },
  {
   "title": "Download (mbps)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "select created_on as time\n, case\n     when download_kbs is null then 0\n     else download_kbs / 1024.0\nend as download_mbps\nfrom bandwidth_metric;"
    }
   ]
  },
  {
   "title": "Upload (mbps)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "select created_on as time\n, case\n     when upload_kbs is null then 0\n     else upload_kbs / 1024.0\nend as upload_mbps\nfrom bandwidth_metric;"
    }
   ]
  }
 ]
}